Repository subsurface/subsurface, pull requests merged in 2018-07, with the labels that each got.

#1450 Dive pictures: remove unnecessary check for no dives
  qt-models/divepicturemodel.cpp
Labels: bug-fix, code-cleanup, dive-photos

#1455 [RFC] Translations: unify gettextFromC::tr() and QObject::tr()
  core/divelogexportlogic.cpp
  core/divesite-helper.cpp
  core/gpslocation.h
  core/qthelper.cpp
  core/qthelper.h
  core/subsurface-qt/DiveObjectHelper.cpp
  desktop-widgets/diveplanner.cpp
  desktop-widgets/mainwindow.cpp
  desktop-widgets/simplewidgets.cpp
  desktop-widgets/subsurfacewebservices.cpp
  desktop-widgets/templatelayout.h
Labels: code-cleanup, translation

#1449 [RFC] Dive pictures: detach ProfileWidget2 from DivePictureModel
  core/imagedownloader.cpp
  core/imagedownloader.h
  profile-widget/profilewidget2.cpp
  profile-widget/profilewidget2.h
  qt-models/divepicturemodel.cpp
  qt-models/divepicturemodel.h
Labels: code-cleanup, dive-photos

#1476 CHANGELOG.md: fix bad markdown formatting
  CHANGELOG.md
Labels: bug-fix, documentation

#1495 Dive media: add ".mov" to list of known video extensions
  core/qthelper.cpp
Labels: complexity-low, dive-video

#1501 map-widget: fix chronology of QML class registration
  subsurface-helper.cpp
Labels: bug-fix, priority-high, widget-map

#1508 Disable the WindowContextHelpButtonHint for Qt >=5.10
  core/qt-init.cpp
Labels: qt, ui-desktop

#1516 Dive media: fix stacking of thumbnails in profile plot
  profile-widget/profilewidget2.cpp
Labels: bug-fix, dive-photos, dive-profile, ui-desktop

#1521 Cleanup: simplify dive_getUniqID()
  core/dive.c
  core/dive.h
  core/qthelper.cpp
  desktop-widgets/mainwindow.cpp
Labels: code-cleanup, complexity-low, core

#1519 Cleanups to core/color.[c|hpp]
  core/color.cpp
  core/color.h
  subsurface-desktop-main.cpp
  subsurface-mobile-main.cpp
Labels: code-cleanup, complexity-low

#1510 Dive media: transport dive-id in drag'n'drop events
  desktop-widgets/divepicturewidget.cpp
  profile-widget/profilewidget2.cpp
  qt-models/divepicturemodel.cpp
Labels: code-cleanup, dive-photos

#1524 Fix obvious crashes in UndoCommands
  core/dive.h
  core/divelist.c
  desktop-widgets/undocommands.cpp
  desktop-widgets/undocommands.h
Labels: bug-fix, ui-desktop

#1529 Fetch sqlite from https:// site
  scripts/get-dep-lib.sh
Labels: build-system

#1525 [RFC] Uninline functions in dive.h
  core/dive.c
  core/dive.h
Labels: code-cleanup, core, rfc

#1530 (Trivial) cleanup: remove DiveItem::icon_names member array
  qt-models/divetripmodel.cpp
  qt-models/divetripmodel.h
Labels: code-cleanup, complexity-low

#1539 Update CodingStyle.md: placement of *, & and && declarators
  CodingStyle.md
Labels: documentation, rfc

#1545 (Trivial) cleanup: remove DiveListView::testSlot()
  desktop-widgets/divelistview.cpp
  desktop-widgets/divelistview.h
Labels: code-cleanup, complexity-low

#1549 Cleanup: Make WindowsTitleUpdate a global object
  core/windowtitleupdate.cpp
  core/windowtitleupdate.h
  desktop-widgets/mainwindow.cpp
  desktop-widgets/mainwindow.h
  export-html.cpp
Labels: code-cleanup, complexity-low

#1550 Cleanup: replace virtual by override where appropriate
  core/divesitehelpers.h
  desktop-widgets/btdeviceselectiondialog.h
  desktop-widgets/configuredivecomputerdialog.h
  desktop-widgets/divepicturewidget.h
  desktop-widgets/diveplanner.h
  desktop-widgets/groupedlineedit.h
  desktop-widgets/kmessagewidget.h
  desktop-widgets/locationinformation.h
  desktop-widgets/mainwindow.h
  desktop-widgets/modeldelegates.h
  desktop-widgets/plugins/facebook/facebook_integration.h
  desktop-widgets/preferences/preferences_defaults.h
  desktop-widgets/preferences/preferences_georeference.h
  desktop-widgets/preferences/preferences_graph.h
  desktop-widgets/preferences/preferences_language.h
  desktop-widgets/preferences/preferences_network.h
  desktop-widgets/preferences/preferences_units.h
  desktop-widgets/preferences/preferencesdialog.h
  desktop-widgets/printdialog.h
  desktop-widgets/simplewidgets.h
  desktop-widgets/starwidget.h
  desktop-widgets/statistics/statisticswidget.h
  desktop-widgets/subsurfacewebservices.h
  desktop-widgets/tableview.h
  desktop-widgets/undocommands.h
  profile-widget/divecartesianaxis.h
  profile-widget/diveeventitem.h
  profile-widget/divepixmapitem.h
  profile-widget/diveprofileitem.h
  profile-widget/divetooltipitem.h
  profile-widget/profilewidget2.h
  profile-widget/ruleritem.h
  profile-widget/tankitem.h
  qt-models/cleanertablemodel.h
  qt-models/cylindermodel.h
  qt-models/divecomputerextradatamodel.h
  qt-models/divecomputermodel.h
  qt-models/divepicturemodel.h
  qt-models/diveplannermodel.h
  qt-models/diveplotdatamodel.h
  qt-models/divetripmodel.h
  qt-models/filtermodels.h
  qt-models/models.h
  qt-models/ssrfsortfilterproxymodel.h
  qt-models/tankinfomodel.h
  qt-models/treemodel.h
  qt-models/weightmodel.h
  qt-models/weightsysteminfomodel.h
  qt-models/yearlystatisticsmodel.h
Labels: code-cleanup, complexity-medium
