Repository subsurface/subsurface, pull requests merged in 2018-10, with the labels that each got.

#1748 [TRIVIAL] Mobile: remove all related data when forgetting DCs
  mobile-widgets/qml/Settings.qml
Labels: bug-fix, mobile-ui

#1749 Fix typo in INSTALL file.
  INSTALL
Labels: new-contributor

#1750 [RFC] Import: remove unnecessary processing of dives in DAN import
  core/import-csv.c
Labels: code-cleanup, import, rfc

#1753 Cleanup: don't access downloadTable directly in Uemis-downloader
  core/uemis-downloader.c
Labels: code-cleanup, complexity-low, dive-computer

#1755 [Please Test] Dive information: fix surface interval calculation
  core/divelist.c
  core/divelist.h
  core/statistics.c
  core/statistics.h
  desktop-widgets/tab-widgets/TabDiveInformation.cpp
  desktop-widgets/tab-widgets/maintab.cpp
  export-html.cpp
Labels: bug-fix, complexity-low, dive-details

#1760 Trivial: Leak fix: free taxonomy data in delete_dive_site()
  core/divesite.c
Labels: code-cleanup, complexity-low, dive-site, priority-low

#1764 [BUGFIX] Map: zoom on dive sites when flipping through dive site list
  desktop-widgets/locationinformation.cpp
  desktop-widgets/mainwindow.cpp
  desktop-widgets/mapwidget.cpp
  desktop-widgets/mapwidget.h
  desktop-widgets/tab-widgets/maintab.cpp
  desktop-widgets/tab-widgets/maintab.h
  map-widget/qmlmapwidgethelper.cpp
  map-widget/qmlmapwidgethelper.h
Labels: bug-fix, dive-site, googlemaps, rfc

#1774 [TRIVIAL] Cleanup: remove unused function MainTab::showLocation()
  desktop-widgets/tab-widgets/maintab.cpp
  desktop-widgets/tab-widgets/maintab.h
Labels: code-cleanup, complexity-low, dive-site

#1801 Cleanup: do proper resource management for struct divecomputer
  core/dive.c
Labels: code-cleanup, core, dive-computer, priority-low

#1815 Mobile UI: make SsrfSwitch resizable
  mobile-widgets/qml/SsrfSwitch.qml
Labels: complexity-low, ui-mobile

#1820 [RFC] Dive site: remove webservice code in MainTab::updateDiveSite()
  desktop-widgets/tab-widgets/maintab.cpp
Labels: code-cleanup, dive-site, rfc

#1826 Cleanup: remove dead code in qthelper.cpp
  core/qthelper.cpp
Labels: code-cleanup, complexity-low

#1827 Cleanup: remove declaration of unused signal
  desktop-widgets/locationinformation.h
Labels: code-cleanup, complexity-low

#1833 std99 does not make sense for C++
  CMakeLists.txt
Labels: build-system

#1836 Dive site: fix oversight in 920eb7576f
  desktop-widgets/locationinformation.cpp
Labels: bug-fix, dive-site
