Repository subsurface/subsurface, pull requests merged in 2019-03, with the labels that each got.

#1994 Add support to compile from source on a Raspberry Pi
  CMakeLists.txt
  INSTALL
Labels: new-contributor

#1990 Import: fix infinite loop
  core/divelist.c
Labels: bug-fix, bug-regression, complexity-low, import

#2000 Map: create correct index in updateMapLocationCoordinates()
  qt-models/maplocationmodel.cpp
Labels: bug-fix, widget-map

#2008 Leak fix: make ostcFirmwareCheck a unique_ptr
  desktop-widgets/downloadfromdivecomputer.cpp
  desktop-widgets/downloadfromdivecomputer.h
Labels: code-cleanup

#2007 Minor cleanups in datatrak.c
  core/datatrak.c
Labels: code-cleanup, import

#2022 Ubuntu 18.10 LGTM build
  .lgtm.yml
Labels: new-contributor

#2025 Cleanup: fix printGPSCoords signature and leaks
  core/gpslocation.cpp
  core/load-git.c
  core/parse-xml.c
  core/qthelper.cpp
  core/qthelper.h
  core/subsurface-qt/DiveObjectHelper.cpp
  desktop-widgets/locationinformation.cpp
  desktop-widgets/modeldelegates.cpp
  desktop-widgets/tab-widgets/maintab.cpp
  map-widget/qmlmapwidgethelper.cpp
  mobile-widgets/qmlmanager.cpp
Labels: code-cleanup
