Repository subsurface/subsurface, pull requests merged in 2019-08, with the labels that each got.

#2191 Make git parser (nearly) reentrant
  core/divelist.c
  core/load-git.c
Labels: code-cleanup, core, parser

#2215 Desktop: display trip time on main-tab
  CHANGELOG.md
  desktop-widgets/tab-widgets/maintab.cpp
  desktop-widgets/tab-widgets/maintab.h
Labels: bug-fix, ui-desktop

#2216 Cleanup: replace macro by inline function in gas-model.c
  core/gas-model.c
Labels: code-cleanup, planner

#2228 Core: unconditionally include stdio.h in libdivecomputer.h
  core/libdivecomputer.h
Labels: code-cleanup, complexity-low

#2229 [RFC] Alternative fix to #2221
  mobile-widgets/qml/DownloadFromDiveComputer.qml
Labels: bug-fix, import, ui-mobile

#2241 Mobile: fix bound check in DiveListModel::data()
  qt-models/divelistmodel.cpp
Labels: bug-fix, ui-mobile

#2247 Add BLE name recognition for the Deepblu Cosmiq+
  core/btdiscovery.cpp
Labels: bluetooth-le, dive-computer

#2267 Fix broken windows build with latest MXE
  core/configuredivecomputer.h
  core/dive.c
  core/parse-xml.c
  core/units.c
  core/units.h
  desktop-widgets/downloadfromdivecomputer.cpp
  desktop-widgets/downloadfromdivecomputer.h
  desktop-widgets/tab-widgets/maintab.cpp
  desktop-widgets/tab-widgets/maintab.h
Labels: new-contributor

#2270 Desktop: improve recognition of HTML-notes
  CHANGELOG.md
  desktop-widgets/tab-widgets/maintab.cpp
Labels: bug-fix, dive-details, planner
