Repository subsurface/subsurface, pull requests merged in 2019-02, with the labels that each got.

#1964 [TRIVIAL] Cleanup: remove unused function MainTab::setCurrentLocationIndex
  desktop-widgets/tab-widgets/maintab.cpp
  desktop-widgets/tab-widgets/maintab.h
Labels: code-cleanup, complexity-low

#1960 Cleanup: rename locationInformation.ui -> locationinformation.ui
  desktop-widgets/CMakeLists.txt
  desktop-widgets/locationinformation.h
  desktop-widgets/locationinformation.ui
Labels: code-cleanup

#1966 Minor cleanups concerning dive-sites
  core/divesite.c
  core/divesite.h
Labels: code-cleanup, dive-site

#1980 Filter: implement any-of mode
  desktop-widgets/filterwidget2.cpp
  desktop-widgets/filterwidget2.ui
  qt-models/filtermodels.cpp
  qt-models/filtermodels.h
Labels: dive-filter

#1981 Filter: change default mode for location to any-of
  qt-models/filtermodels.h
Labels: complexity-low, dive-filter

#1988 Fix usage of Derek features
  .DEREK.yml
Labels: github, new-contributor

#1987 Autogroup: make notrip flag work again.
  desktop-widgets/command_divelist.cpp
Labels: bug-fix, bug-regression
