Repository subsurface/subsurface, pull requests merged in 2020-09, with the labels that each got.

#2932 Planner: Properly initialize salinity
  CHANGELOG.md
  core/dive.c
  desktop-widgets/mainwindow.cpp
Labels: planner

#2933 Macro for "gravity conversion"
  core/dive.c
  core/dive.h
Labels: core

#2945 cleanup: remove empty files in desktop-widgets/statistics
  desktop-widgets/CMakeLists.txt
  desktop-widgets/statistics/monthstatistics.cpp
  desktop-widgets/statistics/monthstatistics.h
  desktop-widgets/statistics/statisticsbar.cpp
  desktop-widgets/statistics/statisticsbar.h
  desktop-widgets/statistics/yearstatistics.cpp
  desktop-widgets/statistics/yearstatistics.h
Labels: code-cleanup, complexity-low, statistics

#2949 Disable SAC factor setting for CCR dives
  core/planner.c
  desktop-widgets/diveplanner.cpp
Labels: planner

#2963 media: read timestamp from mvhd header of MP4/QuickTime videos
  CHANGELOG.md
  core/metadata.cpp
Labels: dive-video

#2967 Bailout segment is part of bottom time
  core/planner.c
Labels: planner

#2969 translations: initialize water type strings at run time [Alternative to #2968]
  core/qthelper.cpp
  core/qthelper.h
  desktop-widgets/tab-widgets/TabDiveInformation.cpp
Labels: translation

#2972 cleanup: silence two compiler warnings in git-access.c
  core/git-access.c
Labels: code-cleanup

#2983 [TRIVIAL] cleanup: remove unnecessary includes in divelistview.cpp
  desktop-widgets/divelistview.cpp
Labels: code-cleanup, complexity-low
