Repository subsurface/subsurface, pull requests merged in 2021-01, with the labels that each got.

#3129 statistics: don't reset binner if binner is set
  stats/statsstate.cpp
Labels: bug-fix, statistics

#3139 statistics: add ticks at beginning and end of the axis
  stats/statsaxis.cpp
Labels: statistics

#3145 statistics: add dive-# and mean-depth variables.
  stats/statsvariables.cpp
Labels: statistics

#3142 statistics: fix range in categorical axes
  stats/statsaxis.cpp
Labels: statistics

#3180 Add Diviac conversion to smtk converter CGI script
  scripts/diviac.pl
  scripts/smtk2ssrf.pl
Labels: format-csv, import
