Repository subsurface/subsurface, pull requests merged in 2022-08, with the labels that each got.

#3491 Some Coverity Fixes
  core/import-csv.c
  core/libdivecomputer.c
  core/liquivision.c
  core/uemis-downloader.c
  qt-models/diveplannermodel.cpp
Labels: code-cleanup

#3495 Prefer real data over planned
  .clang-format
  CHANGELOG.md
  core/dive.c
  core/dive.h
Labels: planner, dive-list, statistics, dive-details

#3505 Floating point comparisons
  core/CMakeLists.txt
  core/libdivecomputer.c
  core/parse-xml.c
  core/settings/qPrefDisplay.cpp
  core/settings/qPrefPrivate.cpp
  core/subsurface-float.h
  core/subsurface-string.h
  desktop-widgets/downloadfromdivecomputer.cpp
  mobile-widgets/themeinterface.cpp
  profile-widget/divecartesianaxis.cpp
  profile-widget/qmlprofile.cpp
  tests/testunitconversion.cpp
Labels: code-cleanup

#3509 parser: allow import of dive sites without UUID
  CHANGELOG.md
  core/parse.c
Labels: import, dive-site
