Repository subsurface/subsurface, pull requests merged in 2024-03, with the labels that each got.

#4115 [TRIVIAL(?)] cleanup: remove ominous pointer calculation
  core/import-csv.c
Labels: code-cleanup

#4116 cleanup: use proper size when allocating string
  core/parse-xml.c
Labels: code-cleanup

#4110 cleanup: fix memory leak (probably / untested)
  core/git-access.c
Labels: bug-fix

#4121 core: fix memory leak in tables code
  core/table.h
Labels: core, bug-fix

#4125 profile: fix uninitialized variable in DivePercentageItem
  profile-widget/divepercentageitem.cpp
Labels: bug-fix, code-cleanup

#4129 Correctly initialize string in core/device.cpp
  core/device.cpp
Labels: bug-fix

#4139 CICD: Add Downloader and smtk2ssrf Build to the CI Pipeline.
  .github/workflows/linux-jammy-5.15.yml
Labels: continuous-integration

#4133 Import / Export: Remove Unsafe XML Handling Options.
  core/parse-xml.cpp
  core/save-xml.cpp
  core/uploadDiveLogsDE.cpp
Labels: parser

#4143 desktop: fix crash in mainwindow.cpp
  desktop-widgets/mainwindow.cpp
  desktop-widgets/mainwindow.h
Labels: cloud-storage, bug-fix

#4142 [TRIVIAL?] cleanup: remove picturedir_string()
  core/qthelper.cpp
  core/qthelper.h
  core/subsurfacestartup.cpp
Labels: code-cleanup

#4144 [TRIVIAL] cleanup: remove unused global variable filesOnCommandLine
  subsurface-desktop-main.cpp
  subsurface-downloader-main.cpp
Labels: ui-desktop, code-cleanup

#4145 cleanup: remove unused macros in qmlmanager.cpp
  mobile-widgets/qmlmanager.cpp
Labels: code-cleanup

#4151 mobile: fix undo/redo
  mobile-widgets/qmlmanager.cpp
Labels: ui-mobile, bug-fix, undo

#4152 statistics: improve formatting of date axis in day-mode
  CHANGELOG.md
  stats/statsaxis.cpp
Labels: statistics, bug-fix
